# Generated by Django 4.1 on 2022-08-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=26)),
                ('l_name', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('solution', models.CharField(max_length=64)),
                ('riddle', models.CharField(max_length=512)),
                ('location', models.CharField(max_length=64)),
                ('tags', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=26)),
                ('hash', models.CharField(max_length=64)),
                ('d0p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d1puzzle', to='api.puzzle')),
                ('d1p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d2puzzle', to='api.puzzle')),
                ('d2p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d3puzzle', to='api.puzzle')),
                ('d3p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d4puzzle', to='api.puzzle')),
                ('d4p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d5puzzle', to='api.puzzle')),
                ('d5p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d6puzzle', to='api.puzzle')),
                ('d6p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d7puzzle', to='api.puzzle')),
                ('d7p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d8puzzle', to='api.puzzle')),
                ('d8p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d9puzzle', to='api.puzzle')),
                ('d9p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d10puzzle', to='api.puzzle')),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.puzzle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
