# Generated by Django 4.1 on 2022-08-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='fixme@change.com', max_length=256),
        ),
        migrations.AddField(
            model_name='member',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='url',
            field=models.URLField(default='fixme.com', max_length=256),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='value',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='solve',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='solve',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='d0f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d1f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d2f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d3f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d4f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d5f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d6f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d7f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d8f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='d9f',
            field=models.BooleanField(default=False),
        ),
    ]
