# Generated by Django 4.1 on 2022-08-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member_email_member_is_owner_puzzle_url_puzzle_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
