# Generated by Django 4.1 on 2022-08-12 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_is_owner_member_is_team_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('s_time', models.DateTimeField(null=True)),
                ('solved', models.BooleanField(default=False)),
                ('found', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('s_date', models.DateTimeField(null=True)),
                ('e_date', models.DateTimeField(null=True)),
                ('points', models.IntegerField(default=100)),
                ('solution', models.CharField(max_length=64)),
                ('hint', models.CharField(max_length=512, null=True)),
                ('tags', models.CharField(max_length=256, null=True)),
                ('location', models.CharField(max_length=64, null=True)),
                ('url_slug', models.SlugField(default='default-slug', max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='solve',
            name='puzzle',
        ),
        migrations.RemoveField(
            model_name='solve',
            name='team',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='is_team_owner',
            new_name='is_owner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d0f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d0p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d1f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d1p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d2f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d2p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d3f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d3p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d4f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d4p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d5f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d5p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d6f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d6p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d7f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d7p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d8f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d8p',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d9f',
        ),
        migrations.RemoveField(
            model_name='team',
            name='d9p',
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Puzzle',
        ),
        migrations.DeleteModel(
            name='Solve',
        ),
        migrations.AddField(
            model_name='assignment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedMember', to='api.member'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='s_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solvingMember', to='api.member'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
