# Generated by Django 4.1 on 2022-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_assignment_event_remove_solve_puzzle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='s_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hint',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
