# Generated by Django 4.1 on 2022-08-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_assignment_index_alter_assignment_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='url_slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='uname',
            field=models.CharField(max_length=26, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=26, unique=True),
        ),
    ]
