# Generated by Django 4.1 on 2022-08-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='e_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='s_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
